import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, User } from 'firebase/auth';
import { getFirestore, doc, getDoc } from 'firebase/firestore';
import { UserProfile } from '@/types';
import firebaseConfig from '../../firebase-applet-config.json';

// Initialize Firebase using the config generated by the setup tool
const app = getApps().length > 0 ? getApp() : initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const db = getFirestore(app, (firebaseConfig as any).firestoreDatabaseId);
export const googleProvider = new GoogleAuthProvider();

const getGooglePhotoURL = (user: any): string => {
  if (!user) return '';
  
  if (user.photoURL) return user.photoURL;
  
  if (user.user_metadata) {
    if (user.user_metadata.avatar_url) return user.user_metadata.avatar_url;
    if (user.user_metadata.picture) return user.user_metadata.picture;
    if (user.user_metadata.photoURL) return user.user_metadata.photoURL;
  }
  
  if (user.raw_user_meta_data) {
    if (user.raw_user_meta_data.avatar_url) return user.raw_user_meta_data.avatar_url;
    if (user.raw_user_meta_data.picture) return user.raw_user_meta_data.picture;
    if (user.raw_user_meta_data.photoURL) return user.raw_user_meta_data.photoURL;
  }
  
  if (user.identity_data) {
    if (user.identity_data.avatar_url) return user.identity_data.avatar_url;
    if (user.identity_data.picture) return user.identity_data.picture;
  }
  
  if (user.providerData && user.providerData.length > 0) {
    for (const provider of user.providerData) {
      if (provider.photoURL) return provider.photoURL;
      if (provider.user_metadata?.avatar_url) return provider.user_metadata.avatar_url;
      if (provider.raw_user_meta_data?.avatar_url) return provider.raw_user_meta_data.avatar_url;
    }
  }

  return '';
};

export async function getUserProfile(user: User): Promise<UserProfile | null> {
  const docRef = doc(db, 'users', user.uid);
  const docSnap = await getDoc(docRef);
  
  if (docSnap.exists()) {
    return { uid: user.uid, ...docSnap.data() } as UserProfile;
  }
  
  return {
    uid: user.uid,
    email: user.email || '',
    role: 'USER',
    displayName: user.displayName || '',
    photoURL: getGooglePhotoURL(user),
    createdAt: Date.now()
  };
}
